[application]

[web.app]
title = "Snow Years Comparison"
base_path = "chart-snow-years"

[web.resource]
style = []
script = [
  "https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js",
]

[web.resource.dev]
script = []
