[application]

[web.app]
title = "Historical Snow Water Equivalent by Sensor"

[web.resource]
style = []
script = [
  "https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js",
]

[web.resource.dev]
script = []
