[application]

[web.app]
title = "Snow Year Statistics Table"
base_path = "table-snow-stats"

[web.resource]
style = []
script = [
  "https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js",
]

[web.resource.dev]
script = []
